version: '3.9'
services:
  lhr:
    container_name: lhr
    build:
      context: .
      target: runtime
      args: [EXE_NAME=network]
    privileged: true
    ports: [8080:8080]
    networks: ["network"]

networks:
  network:
    name: network

