version: '3'

vars:
  CONFIG: docker-compose.yml

tasks:
  default:
    desc: list tasks
    cmds:
      - task --list-all

  htmx:
    desc: install htmx@latest
    cmds:
      - curl -Ls -o static/htmx.min.js https://unpkg.com/htmx.org@1.9.8


  cache:
    desc: cache dependencies
    cmds:
      - go mod tidy

  stop:
    desc: terminate application
    cmds:
      - docker-compose down --volumes

  start:
    desc: run application
    deps:
      - stop
      - cache
    cmds:
      - docker-compose up -d --build --force-recreate

  logs:
    desc: list logs
    cmds:
      - docker-compose logs -f
